-- ================================================================
-- Migration 006: Guests/Check-ins + Notification Log
-- Backs the responsive upload engine + WhatsApp automation.
-- Safe to re-run (idempotent). Run AFTER 005.
-- ================================================================

-- updated_at helper (idempotent)
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- ── 1. guests / daily check-ins ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.guests (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  phone        TEXT,
  room         TEXT,
  room_type    TEXT NOT NULL DEFAULT 'standard'
                 CHECK (room_type IN ('standard', 'suite')),
  arrival_date DATE,
  status       TEXT NOT NULL DEFAULT 'expected'
                 CHECK (status IN ('expected', 'room_ready', 'checked_in')),
  checkin_time TIMESTAMPTZ,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_guests_updated ON public.guests;
CREATE TRIGGER trg_guests_updated
  BEFORE UPDATE ON public.guests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_guests_arrival ON public.guests (arrival_date);
CREATE INDEX IF NOT EXISTS idx_guests_status  ON public.guests (status);

-- ── 2. notification_log (idempotency for WhatsApp triggers) ───────────────────
CREATE TABLE IF NOT EXISTS public.notification_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guest_id     BIGINT REFERENCES public.guests(id) ON DELETE CASCADE,
  recipient    TEXT,                          -- phone / employee id (free text)
  trigger_type TEXT NOT NULL,                 -- night_before | morning_suite |
                                              -- room_ready | butler_1h | shift_assignment
  channel      TEXT NOT NULL DEFAULT 'whatsapp',
  status       TEXT NOT NULL DEFAULT 'sent'   -- sent | simulated | failed
                 CHECK (status IN ('sent', 'simulated', 'failed')),
  payload      JSONB,
  sent_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One guest-trigger pair fires at most once (NULL guest_id rows are unconstrained,
-- e.g. staff shift_assignment messages).
CREATE UNIQUE INDEX IF NOT EXISTS uq_notif_guest_trigger
  ON public.notification_log (guest_id, trigger_type)
  WHERE guest_id IS NOT NULL;

-- ── 3. RLS ───────────────────────────────────────────────────────────────────
ALTER TABLE public.guests           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS guests_rw ON public.guests;
CREATE POLICY guests_rw ON public.guests
  FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- Reads for the dashboard; writes happen via the service-role edge functions
-- (service role bypasses RLS).
DROP POLICY IF EXISTS notif_read ON public.notification_log;
CREATE POLICY notif_read ON public.notification_log
  FOR SELECT TO authenticated
  USING (true);

-- ================================================================
-- END OF MIGRATION 006
-- ================================================================
