-- ================================================================
-- Migration 010: WhatsApp conversation history
-- Stores all inbound (customer→bot) and outbound (bot→customer)
-- WhatsApp messages for the conversation inbox UI.
-- Safe to re-run (idempotent).
-- ================================================================

CREATE TABLE IF NOT EXISTS public.whatsapp_conversations (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone       TEXT    NOT NULL,                           -- E.164: +972XXXXXXXXX
  guest_id    BIGINT  REFERENCES public.guests(id) ON DELETE SET NULL,
  direction   TEXT    NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  message     TEXT    NOT NULL,
  wa_message_id TEXT,                                    -- Meta message ID (dedup)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wa_conv_phone ON public.whatsapp_conversations (phone, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wa_conv_guest ON public.whatsapp_conversations (guest_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_wa_conv_wa_id
  ON public.whatsapp_conversations (wa_message_id)
  WHERE wa_message_id IS NOT NULL;  -- prevent duplicate inbound events from Meta

ALTER TABLE public.whatsapp_conversations ENABLE ROW LEVEL SECURITY;

-- All authenticated managers can read conversations
DROP POLICY IF EXISTS wa_conv_read ON public.whatsapp_conversations;
CREATE POLICY wa_conv_read ON public.whatsapp_conversations
  FOR SELECT USING (auth.role() = 'authenticated');

-- Only service role (Edge Functions) can write
DROP POLICY IF EXISTS wa_conv_write ON public.whatsapp_conversations;
CREATE POLICY wa_conv_write ON public.whatsapp_conversations
  FOR INSERT WITH CHECK (auth.role() = 'service_role');
