-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 012 — Concierge Alert System
-- Dream Island AI System
--
-- Adds:
--   1. guests.requires_attention       — boolean flag raised by complaint bot
--   2. whatsapp_conversations.intent   — classified intent per message
--   3. guest_alerts                    — duty-manager dashboard alert table
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. guests — attention-flagging columns ───────────────────────────────────
ALTER TABLE public.guests
  ADD COLUMN IF NOT EXISTS requires_attention       BOOLEAN     NOT NULL DEFAULT false;
ALTER TABLE public.guests
  ADD COLUMN IF NOT EXISTS requires_attention_since TIMESTAMPTZ;

-- Dashboard query: SELECT * FROM guests WHERE requires_attention = true
CREATE INDEX IF NOT EXISTS idx_guests_attention
  ON public.guests(requires_attention, requires_attention_since DESC)
  WHERE requires_attention = true;

-- ── 2. whatsapp_conversations — intent classification column ─────────────────
-- Values: 'complaint' | 'upsell' | 'faq' | 'fallback'
ALTER TABLE public.whatsapp_conversations
  ADD COLUMN IF NOT EXISTS intent TEXT;

CREATE INDEX IF NOT EXISTS idx_wa_conv_intent
  ON public.whatsapp_conversations(intent, created_at DESC)
  WHERE intent IS NOT NULL;

-- ── 3. guest_alerts — duty-manager alert table ───────────────────────────────
-- Every time the bot detects a complaint it inserts a row here.
-- Staff resolve rows from the dashboard.
CREATE TABLE IF NOT EXISTS public.guest_alerts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Guest may be unknown (walk-in / unregistered phone)
  guest_id         BIGINT      REFERENCES public.guests(id) ON DELETE SET NULL,
  phone            TEXT        NOT NULL,

  -- Type of alert: 'complaint' | 'upsell_opportunity' | 'request'
  alert_type       TEXT        NOT NULL DEFAULT 'complaint',

  -- Original guest message that triggered the alert
  message          TEXT        NOT NULL,

  -- Link back to the whatsapp_conversations row for full context
  conversation_id  BIGINT      REFERENCES public.whatsapp_conversations(id) ON DELETE SET NULL,

  -- Resolution tracking
  resolved         BOOLEAN     NOT NULL DEFAULT false,
  resolved_by      UUID,                -- profiles.id of staff member
  resolved_at      TIMESTAMPTZ,
  resolution_notes TEXT,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast dashboard query: "all unresolved alerts, newest first"
CREATE INDEX IF NOT EXISTS idx_guest_alerts_unresolved
  ON public.guest_alerts(resolved, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_guest_alerts_guest
  ON public.guest_alerts(guest_id)
  WHERE guest_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_guest_alerts_phone
  ON public.guest_alerts(phone, created_at DESC);

-- ── 4. RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE public.guest_alerts ENABLE ROW LEVEL SECURITY;

-- Authenticated staff (managers) can read and update (resolve) alerts
DROP POLICY IF EXISTS "guest_alerts_read"   ON public.guest_alerts;
DROP POLICY IF EXISTS "guest_alerts_update" ON public.guest_alerts;
DROP POLICY IF EXISTS "guest_alerts_insert" ON public.guest_alerts;

CREATE POLICY "guest_alerts_read"
  ON public.guest_alerts FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "guest_alerts_update"
  ON public.guest_alerts FOR UPDATE
  USING (auth.role() = 'authenticated');

-- Inserts come from Edge Functions (service role — bypasses RLS automatically)
-- This policy is a safety net if called from a client with auth token:
CREATE POLICY "guest_alerts_insert"
  ON public.guest_alerts FOR INSERT
  WITH CHECK (auth.role() IN ('authenticated', 'service_role'));
