-- supabase/migrations/023_pre_arrival_automation.sql
-- Pre-arrival automation flow columns:
--   T-2 days  : dream_pre_arrival_confirm
--   On "כן"   : dream_payment_link + dream_workshop_signup
--   Arrival AM: dream_morning_welcome

ALTER TABLE public.guests
  ADD COLUMN IF NOT EXISTS arrival_confirmed        BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS msg_pre_arrival_2d_sent  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS msg_morning_welcome_sent BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS payment_amount           NUMERIC,
  ADD COLUMN IF NOT EXISTS payment_link_url         TEXT;

COMMENT ON COLUMN public.guests.arrival_confirmed        IS 'True after guest replies כן to dream_pre_arrival_confirm';
COMMENT ON COLUMN public.guests.msg_pre_arrival_2d_sent  IS 'True once dream_pre_arrival_confirm was sent (T-2 days)';
COMMENT ON COLUMN public.guests.msg_morning_welcome_sent IS 'True once dream_morning_welcome was sent (morning of arrival)';
COMMENT ON COLUMN public.guests.payment_amount           IS 'ILS amount from suite-arrivals Excel upload';
COMMENT ON COLUMN public.guests.payment_link_url         IS 'Payment URL generated by payment API (nullable until integrated)';
