-- 031_treatment_time.sql
-- יוצר טבלת bookings לייבוא נתוני EZGO (הגעות + ספא)
-- כולל treatment_time ו-treatment_type לשילוב בהודעת האישור

CREATE TABLE IF NOT EXISTS public.bookings (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guest_name     TEXT,
  phone          TEXT    NOT NULL,
  arrival_date   DATE    NOT NULL,
  checkout_date  DATE,
  nights         INT,
  amount         NUMERIC,
  treatment_time TEXT,
  treatment_type TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (phone, arrival_date)
);

CREATE INDEX IF NOT EXISTS idx_bookings_phone        ON public.bookings (phone);
CREATE INDEX IF NOT EXISTS idx_bookings_arrival_date ON public.bookings (arrival_date);

DROP TRIGGER IF EXISTS trg_bookings_updated ON public.bookings;
CREATE TRIGGER trg_bookings_updated
  BEFORE UPDATE ON public.bookings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth users can read bookings"  ON public.bookings FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth users can insert bookings" ON public.bookings FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth users can update bookings" ON public.bookings FOR UPDATE TO authenticated USING (true);

COMMENT ON TABLE public.bookings IS 'הגעות מיובאות מ-EZGO דרך Make.com — ניתנות לעריכה ידנית';
COMMENT ON COLUMN public.bookings.treatment_time IS 'שעת טיפול ספא — מדוח פעילויות EZGO';
COMMENT ON COLUMN public.bookings.treatment_type IS 'סוג טיפול ספא — מדוח פעילויות EZGO';
