-- 035_spa_staging.sql
-- טבלת ביניים לסנכרון לוח ספא — מנהל מאשר לפני כתיבה ל-bookings

CREATE TABLE IF NOT EXISTS public.spa_staging (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch      UUID        NOT NULL DEFAULT gen_random_uuid(),
  imported_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- נתונים שחולצו מהמייל
  treatment_time    TEXT,
  treatment_type    TEXT,
  guest_name        TEXT,
  phone             TEXT,
  raw_extras        TEXT,

  -- תוצאת ההתאמה מול bookings
  matched_booking_id BIGINT     REFERENCES public.bookings(id) ON DELETE SET NULL,
  match_status       TEXT       NOT NULL DEFAULT 'pending'
    CHECK (match_status IN ('matched', 'no_booking', 'suspicious')),
  suspicious_reason  TEXT,

  -- החלטת מנהל
  sync_status        TEXT       NOT NULL DEFAULT 'pending'
    CHECK (sync_status IN ('pending', 'approved', 'rejected', 'synced')),
  reviewed_at        TIMESTAMPTZ,

  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_spa_staging_batch       ON public.spa_staging (import_batch);
CREATE INDEX IF NOT EXISTS idx_spa_staging_sync_status ON public.spa_staging (sync_status);
CREATE INDEX IF NOT EXISTS idx_spa_staging_phone       ON public.spa_staging (phone);

ALTER TABLE public.spa_staging ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth users can read spa_staging"   ON public.spa_staging;
DROP POLICY IF EXISTS "auth users can insert spa_staging" ON public.spa_staging;
DROP POLICY IF EXISTS "auth users can update spa_staging" ON public.spa_staging;

CREATE POLICY "auth users can read spa_staging"
  ON public.spa_staging FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth users can insert spa_staging"
  ON public.spa_staging FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth users can update spa_staging"
  ON public.spa_staging FOR UPDATE TO authenticated USING (true);

COMMENT ON TABLE  public.spa_staging              IS 'שלב ביניים לייבוא לוח ספא — ממתין לאישור מנהל';
COMMENT ON COLUMN public.spa_staging.match_status  IS 'matched=נמצא בהגעות, no_booking=לא קיים, suspicious=טלפון משותף/בעיה';
COMMENT ON COLUMN public.spa_staging.sync_status   IS 'pending=ממתין, approved=אושר, rejected=נדחה, synced=נכתב ל-bookings';
