-- =============================================================================
-- 072_ai_failover_events.sql
-- ai_failover_events — visible record of every automatic Claude↔Gemini
-- failover in the guest concierge path, so AiFailoverWidget.js can surface a
-- real-time "⚠️ Gemini limit hit → failed over to Claude" alert on the
-- dashboard instead of the event only ever existing in Edge Function logs.
--
-- Written by whatsapp-webhook/index.ts's existing engine-failover catch
-- block (resolveModelRoute() + try/catch around callClaude()/askGemini()) —
-- that logic already worked before this migration; this only adds
-- visibility, it does not change failover behavior itself.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.ai_failover_events (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  from_engine   TEXT NOT NULL,             -- the engine that failed ('claude' | 'gemini')
  to_engine     TEXT NOT NULL,             -- the engine that took over
  error_message TEXT,
  guest_phone   TEXT
);

CREATE INDEX IF NOT EXISTS idx_ai_failover_events_occurred ON public.ai_failover_events (occurred_at DESC);

ALTER TABLE public.ai_failover_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ai_failover_events_read" ON public.ai_failover_events;
CREATE POLICY "ai_failover_events_read" ON public.ai_failover_events
  FOR SELECT TO authenticated USING (true);

-- Inserted by whatsapp-webhook using the service-role key — no insert policy
-- needed for the anon/authenticated roles, same convention as notification_log.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'ai_failover_events'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_failover_events;
  END IF;
END $$;
