-- Migration 084: Guest Portal CMS — portal_scenes table
-- Session "Dynamic CMS, Vercel Asset Fix, & Luxury UX Flow".
--
-- Replaces the hardcoded src/data/portalContent.js as the LIVE source for
-- the Guest Portal's scrollytelling scenes — that file remains in the repo
-- as the static fallback PhotoTour.js uses only if this table's fetch fails
-- or returns zero rows (offline-safe, never a blank portal).
--
-- RLS is intentionally PUBLIC READ: this is marketing copy + image
-- filenames shown to any guest who opens a portal link — not guest PII, not
-- sensitive, the same trust level as the static bundle it replaces. Writes
-- are admin-only via the existing get_my_role() helper (migration 003),
-- which already normalizes both 'admin' and 'super_admin' to 'admin'.
CREATE TABLE IF NOT EXISTS public.portal_scenes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort_order  INT         NOT NULL DEFAULT 0,
  image       TEXT        NOT NULL,           -- filename only, e.g. "spa.jpg" — PhotoTour.js prefixes /images/
  title       TEXT        NOT NULL,
  body        TEXT        NOT NULL,
  -- Array of { label, actionType: "REQUEST"|"LINK", upsellLabel?, buttonUrl? }
  -- — same shape as portalContent.js's ctas, see that file's header comment.
  ctas        JSONB       NOT NULL DEFAULT '[]'::jsonb,
  is_active   BOOLEAN     NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_portal_scenes_order ON public.portal_scenes (sort_order) WHERE is_active = true;

DROP TRIGGER IF EXISTS trg_portal_scenes_updated_at ON public.portal_scenes;
CREATE TRIGGER trg_portal_scenes_updated_at
  BEFORE UPDATE ON public.portal_scenes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.portal_scenes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS portal_scenes_public_read ON public.portal_scenes;
CREATE POLICY portal_scenes_public_read ON public.portal_scenes
  FOR SELECT USING (true);

DROP POLICY IF EXISTS portal_scenes_admin_write ON public.portal_scenes;
CREATE POLICY portal_scenes_admin_write ON public.portal_scenes
  FOR ALL
  USING      (get_my_role() = 'admin' OR auth.role() = 'service_role')
  WITH CHECK (get_my_role() = 'admin' OR auth.role() = 'service_role');

-- ── Seed: the 7-scene "Luxury UX Flow" content, sourced from
-- dream-island.co.il where real copy exists (see comments per row) — same
-- discipline as portalContent.js's existing scenes, not generic resort copy.
-- Guarded by "table is currently empty" (no unique column to ON CONFLICT
-- against — sort_order/image are intentionally editable, not unique keys)
-- so re-running this migration never duplicates rows.
INSERT INTO public.portal_scenes (sort_order, image, title, body, ctas)
SELECT v.sort_order, v.image, v.title, v.body, v.ctas::jsonb
FROM (VALUES
  (10, 'entrance.jpg', 'אי של תענוגות החיים',
   'ברוכים הבאים לדרים איילנד! חופשה שתישאר עמכם הרבה אחרי שתחזרו הביתה, כל פרט תוכנן בשביל לספק לכם חוויה ועונג בלתי מתפשר',
   '[]'),
  (20, 'insidepool.jpg', 'מתחם המים',
   'מים הם מקור החיים המשרים שקט ושלווה. בריכות זרמים, מתחמים מקורים ופתוחים, ו-20 חדרי טיפולים יוקרתיים ב-DREAM SPA ו-SPA EVENU.',
   '[{"label": "💆 בואו נשריין לכם טיפול", "actionType": "REQUEST", "upsellLabel": "בקשת טיפול ספא"}]'),
  (30, 'premiumday.jpg', 'בילוי יומי פרימיום',
   'חווית בילוי יומי בריזורט — PREMIUM DAY מפנק עם גישה למתחמי הבריכות והספא, ליום שלם של פינוק בלי לינה.',
   '[{"label": "🌟 להזמנת בילוי יומי", "actionType": "LINK", "buttonUrl": "https://www.dream-island.co.il/orderonline"}]'),
  (40, 'wine.jpg', 'אוכל הוא תשוקה ואהבה לחיים',
   'מסעדת ערמונים מפליאה במנות מרתקות, ופוד-טראקים מפתיעים את האורחים בכל פינה באי.',
   '[{"label": "🍷 נשמח לארח אתכם בסדנת יין", "actionType": "LINK", "buttonUrl": "https://go.oncehub.com/DreamIsland"}, {"label": "🍾 שמפניה מחכה בסוויטה", "actionType": "REQUEST", "upsellLabel": "שמפניה לסוויטה"}]'),
  (50, 'padel.jpg', 'אורח חיים פעיל',
   'מגרשי פאדל מחכים לכם למשחק תחת השמש — מומלץ לשריין מקום מראש.',
   '[{"label": "🎾 בקשת שיריון מגרש", "actionType": "REQUEST", "upsellLabel": "בקשת שיריון מגרש פאדל"}]'),
  (60, 'chill.jpg', 'מתחמי מנוחה',
   'מתחמי מנוחה פסטוריליים פזורים בין שטחי האי — פינות צל ושלווה לרגעים של כלום-לעשות.',
   '[]'),
  (70, 'suites.jpg', '26 אבני חן',
   '26 סוויטות בוטיק יוקרתיות, כל אחת כאבן חן ייחודית — הרמוניה עדינה בין אלגנטיות, יופי, סטייל, פינוקים ושפע.',
   '[{"label": "✨ בואו נשריין לכם שדרוג", "actionType": "REQUEST", "upsellLabel": "בקשת שדרוג סוויטה"}]')
) AS v(sort_order, image, title, body, ctas)
WHERE NOT EXISTS (SELECT 1 FROM public.portal_scenes);
