-- ============================================================================
-- Voucher Reconciliation Engine (Yelena)
-- ============================================================================
-- Scope: reconcile the "EasyGo Vouchers Report" (what staff booked) against
-- external "Provider Reports" (Excel/PDF from Hightech Zone, Dolce Vita,
-- Pais Plus, Hever, Nofshonit, etc. — the source of truth for what package
-- the guest actually paid for).
--
-- Does NOT touch ezgoParser.js / the existing arrivals import pipeline.
-- This is a wholly separate set of tables, separate from suite_rooms/bookings.
--
-- Dynamic Onboarding (Yelena maps a new provider's columns once): reuses the
-- EXISTING import_mapping_memory table (migration 049) — it already stores
-- exactly (schema_key, header_signature) -> approved_mapping JSONB, which is
-- the same "map once, remember by header shape" mechanism this feature needs.
-- No new memory table. Use schema_key = 'voucher_provider_report' for
-- provider-side files and 'voucher_easygo_report' for the EasyGo export
-- (header_signature already differentiates between providers whose column
-- layouts differ — no per-provider schema_key needed).
-- agent_memory (manager_id/rule_text/category) is NOT used here — it's a
-- different table for AI persona/behavioral rules, not column mappings.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. voucher_providers — registry of external voucher providers + their
--    matching rule. Data-driven on purpose: adding a 6th provider later is a
--    row insert, not a code change/redeploy.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.voucher_providers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_name TEXT        NOT NULL UNIQUE,
  match_mode    TEXT        NOT NULL DEFAULT 'exact'
                CHECK (match_mode IN ('exact', 'truncate_4')),
  is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by    UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

COMMENT ON COLUMN public.voucher_providers.match_mode IS
  'exact = full voucher number must match character-for-character. truncate_4 = ignore the LAST 4 digits of the EasyGo-side voucher number when comparing to this provider''s voucher number. Per Mike''s rule: truncate_4 applies ONLY to Hightech Zone / Dolce Vita / Pais Plus — every other provider (Hever, Nofshonit, etc.) defaults to exact. An unrecognized/未来 mode falls back to exact in voucher_numbers_match() — fail-safe, never fail-open.';
COMMENT ON COLUMN public.voucher_providers.is_active IS
  'Providers are deactivated, never deleted — historical reports keep a valid FK. See voucher_provider_reports.provider_id (ON DELETE RESTRICT).';

-- Seed the 5 providers named in the spec. Idempotent — safe to re-run.
INSERT INTO public.voucher_providers (provider_name, match_mode) VALUES
  ('Hightech Zone', 'truncate_4'),
  ('Dolce Vita',     'truncate_4'),
  ('Pais Plus',      'truncate_4'),
  ('Hever',          'exact'),
  ('Nofshonit',      'exact')
ON CONFLICT (provider_name) DO NOTHING;

ALTER TABLE public.voucher_providers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth users can read voucher_providers"
  ON public.voucher_providers FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth users can insert voucher_providers"
  ON public.voucher_providers FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth users can update voucher_providers"
  ON public.voucher_providers FOR UPDATE TO authenticated USING (true);
-- No DELETE policy anywhere in this file, by design — see Zero Data Loss note below.

-- ----------------------------------------------------------------------------
-- 2. voucher_provider_reports — parsed rows from the Provider Report.
--    This is the SOURCE OF TRUTH side (what the guest actually paid for).
--    voucher_number is nullable on purpose: a row that fails to yield a
--    voucher number is still inserted and surfaced as an 'unparseable'
--    exception later, never silently dropped (Zero Data Loss, §0.1).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.voucher_provider_reports (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch     UUID        NOT NULL DEFAULT gen_random_uuid(),
  provider_id      BIGINT      NOT NULL REFERENCES public.voucher_providers(id) ON DELETE RESTRICT,
  voucher_number   TEXT,
  guest_name       TEXT,
  package_type     TEXT,
  amount           NUMERIC,
  purchase_date    DATE,
  raw_extras       JSONB,                 -- any source columns with no dedicated field — nothing is discarded on import
  source_file_name TEXT,
  imported_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by       UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_voucher_provider_reports_batch    ON public.voucher_provider_reports (import_batch);
CREATE INDEX IF NOT EXISTS idx_voucher_provider_reports_voucher  ON public.voucher_provider_reports (voucher_number);
CREATE INDEX IF NOT EXISTS idx_voucher_provider_reports_provider ON public.voucher_provider_reports (provider_id);

ALTER TABLE public.voucher_provider_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth users can read voucher_provider_reports"
  ON public.voucher_provider_reports FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth users can insert voucher_provider_reports"
  ON public.voucher_provider_reports FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth users can update voucher_provider_reports"
  ON public.voucher_provider_reports FOR UPDATE TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- 3. voucher_easygo_records — parsed rows from the "EasyGo Vouchers Report".
--    This is the STAFF-BOOKED side. provider_id is nullable: the EasyGo
--    export may not cleanly label which provider a row belongs to — the
--    reconciliation run treats a NULL provider_id as "try every provider's
--    rule", never as a reason to reject the row at import time.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.voucher_easygo_records (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch     UUID        NOT NULL DEFAULT gen_random_uuid(),
  provider_id      BIGINT      REFERENCES public.voucher_providers(id) ON DELETE SET NULL,
  voucher_number   TEXT,
  guest_name       TEXT,
  phone            TEXT,
  order_number     TEXT,
  guest_id         BIGINT      REFERENCES public.guests(id) ON DELETE SET NULL,
  package_type     TEXT,
  amount           NUMERIC,
  arrival_date     DATE,
  raw_extras       JSONB,
  source_file_name TEXT,
  imported_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by       UUID        REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_voucher_easygo_records_batch    ON public.voucher_easygo_records (import_batch);
CREATE INDEX IF NOT EXISTS idx_voucher_easygo_records_voucher  ON public.voucher_easygo_records (voucher_number);
CREATE INDEX IF NOT EXISTS idx_voucher_easygo_records_provider ON public.voucher_easygo_records (provider_id);
CREATE INDEX IF NOT EXISTS idx_voucher_easygo_records_guest    ON public.voucher_easygo_records (guest_id);

ALTER TABLE public.voucher_easygo_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth users can read voucher_easygo_records"
  ON public.voucher_easygo_records FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth users can insert voucher_easygo_records"
  ON public.voucher_easygo_records FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth users can update voucher_easygo_records"
  ON public.voucher_easygo_records FOR UPDATE TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- 4. voucher_reconciliation_results — one row per comparison outcome.
--    Mirrors spa_staging's dual-status triage convention: match_status is the
--    machine classification, review_status is the human decision. Every
--    provider row and every EasyGo row ends up represented here after a run
--    — including clean matches — so nothing is ever silently absent from
--    the review screen (FAIL VISIBLE, §0.3).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.voucher_reconciliation_results (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reconciliation_run_id  UUID        NOT NULL,
  provider_report_id     BIGINT      REFERENCES public.voucher_provider_reports(id) ON DELETE CASCADE,
  easygo_record_id       BIGINT      REFERENCES public.voucher_easygo_records(id) ON DELETE CASCADE,
  provider_id            BIGINT      REFERENCES public.voucher_providers(id) ON DELETE SET NULL,
  match_status           TEXT        NOT NULL
                          CHECK (match_status IN (
                            'matched', 'package_mismatch', 'duplicate_match',
                            'missing_in_easygo', 'missing_in_provider', 'unparseable'
                          )),
  match_basis            TEXT        CHECK (match_basis IN ('exact', 'truncate_4')),
  discrepancy_note       TEXT,
  review_status          TEXT        NOT NULL DEFAULT 'pending'
                          CHECK (review_status IN ('pending', 'approved', 'rejected', 'resolved')),
  reviewed_by            UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at            TIMESTAMPTZ,
  review_note            TEXT,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT voucher_reconciliation_results_has_side
    CHECK (provider_report_id IS NOT NULL OR easygo_record_id IS NOT NULL)
);

COMMENT ON COLUMN public.voucher_reconciliation_results.match_status IS
  'matched = one clean voucher-number match, package agrees. package_mismatch = voucher numbers matched but package_type differs. duplicate_match = more than one EasyGo row matched the same provider voucher (needs a human to pick the right one). missing_in_easygo = provider proves the guest paid, but staff never booked it in EasyGo. missing_in_provider = staff booked it in EasyGo but no provider report backs it up — the financially important case to catch. unparseable = row had no voucher number to compare at all.';
COMMENT ON COLUMN public.voucher_reconciliation_results.review_status IS
  'Human decision layer, independent of match_status — mirrors spa_staging.sync_status. A resolved/approved/rejected row stays in the table forever; it never disappears from history.';

CREATE INDEX IF NOT EXISTS idx_voucher_reconciliation_results_run      ON public.voucher_reconciliation_results (reconciliation_run_id);
CREATE INDEX IF NOT EXISTS idx_voucher_reconciliation_results_status   ON public.voucher_reconciliation_results (match_status);
CREATE INDEX IF NOT EXISTS idx_voucher_reconciliation_results_review  ON public.voucher_reconciliation_results (review_status);
CREATE INDEX IF NOT EXISTS idx_voucher_reconciliation_results_provider ON public.voucher_reconciliation_results (provider_id);

ALTER TABLE public.voucher_reconciliation_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth users can read voucher_reconciliation_results"
  ON public.voucher_reconciliation_results FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth users can insert voucher_reconciliation_results"
  ON public.voucher_reconciliation_results FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth users can update voucher_reconciliation_results"
  ON public.voucher_reconciliation_results FOR UPDATE TO authenticated USING (true);

-- No DELETE policy on ANY of the 4 tables above, by design (Zero Data Loss,
-- §0.1 — this is financial/audit-adjacent data). A provider is deactivated
-- via is_active=false; an exception is resolved via review_status, never
-- removed. Only a superuser running raw SQL outside the app can delete rows.

-- ----------------------------------------------------------------------------
-- 5. voucher_numbers_match() — the strict matching rule as data-driven logic.
--    truncate_4 strips the LAST 4 characters of the EasyGo-side number only
--    (per spec: "ignore the last 4 digits of the EasyGo voucher ID"), never
--    the provider-side number. Falls back to 'exact' for any mode it doesn't
--    recognize — fail-safe, not fail-open.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.voucher_numbers_match(
  p_match_mode        TEXT,
  p_provider_voucher  TEXT,
  p_easygo_voucher    TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_provider_norm TEXT := upper(trim(p_provider_voucher));
  v_easygo_norm   TEXT := upper(trim(p_easygo_voucher));
  v_easygo_prefix TEXT;
BEGIN
  IF v_provider_norm IS NULL OR v_easygo_norm IS NULL
     OR length(v_provider_norm) = 0 OR length(v_easygo_norm) = 0 THEN
    RETURN FALSE;
  END IF;

  IF p_match_mode = 'truncate_4' THEN
    IF length(v_easygo_norm) <= 4 THEN
      RETURN FALSE; -- too short to truncate safely — never match on an empty/garbage prefix
    END IF;
    v_easygo_prefix := left(v_easygo_norm, length(v_easygo_norm) - 4);
    RETURN v_easygo_prefix = v_provider_norm;
  END IF;

  RETURN v_provider_norm = v_easygo_norm; -- 'exact' and any unrecognized mode
END;
$$;

-- ----------------------------------------------------------------------------
-- 6. run_voucher_reconciliation() — compares one provider-report import batch
--    against one EasyGo import batch and writes every outcome (matches AND
--    exceptions) into voucher_reconciliation_results. Mirrors the
--    upsert_inventory_items / sync_suite_arrivals convention: SECURITY
--    DEFINER, RAISE NOTICE per phase for diagnostics, rollback on error.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.run_voucher_reconciliation(
  p_provider_batch UUID,
  p_easygo_batch   UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_run_id                 UUID := gen_random_uuid();
  v_provider_row           public.voucher_provider_reports%ROWTYPE;
  v_easygo_row             public.voucher_easygo_records%ROWTYPE;
  v_provider               public.voucher_providers%ROWTYPE;
  v_matched_easygo_ids     BIGINT[] := ARRAY[]::BIGINT[];
  v_candidate_ids          BIGINT[];
  v_candidate_count        INT;
  v_sole_easygo            public.voucher_easygo_records%ROWTYPE;
  v_matched_count          INT := 0;
  v_mismatch_count         INT := 0;
  v_duplicate_count        INT := 0;
  v_missing_easygo_count   INT := 0;
  v_missing_provider_count INT := 0;
  v_unparseable_count      INT := 0;
BEGIN
  RAISE NOTICE '[run_voucher_reconciliation] -- START run=% provider_batch=% easygo_batch=%',
    v_run_id, p_provider_batch, p_easygo_batch;

  FOR v_provider_row IN
    SELECT * FROM public.voucher_provider_reports WHERE import_batch = p_provider_batch
  LOOP
    IF v_provider_row.voucher_number IS NULL OR length(trim(v_provider_row.voucher_number)) = 0 THEN
      INSERT INTO public.voucher_reconciliation_results
        (reconciliation_run_id, provider_report_id, easygo_record_id, provider_id, match_status, discrepancy_note)
      VALUES
        (v_run_id, v_provider_row.id, NULL, v_provider_row.provider_id, 'unparseable',
         'שורת ספק ללא מספר שובר לקריאה — לא ניתן להשוות');
      v_unparseable_count := v_unparseable_count + 1;
      CONTINUE;
    END IF;

    SELECT * INTO v_provider FROM public.voucher_providers WHERE id = v_provider_row.provider_id;

    SELECT ARRAY_AGG(e.id) INTO v_candidate_ids
    FROM public.voucher_easygo_records e
    WHERE e.import_batch = p_easygo_batch
      AND NOT (e.id = ANY (v_matched_easygo_ids))
      AND e.voucher_number IS NOT NULL
      AND (e.provider_id IS NULL OR e.provider_id = v_provider_row.provider_id)
      AND public.voucher_numbers_match(v_provider.match_mode, v_provider_row.voucher_number, e.voucher_number);

    v_candidate_count := COALESCE(array_length(v_candidate_ids, 1), 0);

    IF v_candidate_count = 0 THEN
      INSERT INTO public.voucher_reconciliation_results
        (reconciliation_run_id, provider_report_id, easygo_record_id, provider_id, match_status, match_basis, discrepancy_note)
      VALUES
        (v_run_id, v_provider_row.id, NULL, v_provider_row.provider_id, 'missing_in_easygo', v_provider.match_mode,
         'יש שובר בדוח הספק (' || v_provider.provider_name || ') שאינו מוזמן בדוח השוברים של EasyGo');
      v_missing_easygo_count := v_missing_easygo_count + 1;

    ELSIF v_candidate_count = 1 THEN
      SELECT * INTO v_sole_easygo FROM public.voucher_easygo_records WHERE id = v_candidate_ids[1];
      v_matched_easygo_ids := v_matched_easygo_ids || v_candidate_ids[1];

      IF v_provider_row.package_type IS NOT NULL AND v_sole_easygo.package_type IS NOT NULL
         AND trim(lower(v_provider_row.package_type)) <> trim(lower(v_sole_easygo.package_type)) THEN
        INSERT INTO public.voucher_reconciliation_results
          (reconciliation_run_id, provider_report_id, easygo_record_id, provider_id, match_status, match_basis, discrepancy_note)
        VALUES
          (v_run_id, v_provider_row.id, v_sole_easygo.id, v_provider_row.provider_id, 'package_mismatch', v_provider.match_mode,
           'חבילה שונה: ספק="' || v_provider_row.package_type || '" / EasyGo="' || v_sole_easygo.package_type || '"');
        v_mismatch_count := v_mismatch_count + 1;
      ELSE
        INSERT INTO public.voucher_reconciliation_results
          (reconciliation_run_id, provider_report_id, easygo_record_id, provider_id, match_status, match_basis)
        VALUES
          (v_run_id, v_provider_row.id, v_sole_easygo.id, v_provider_row.provider_id, 'matched', v_provider.match_mode);
        v_matched_count := v_matched_count + 1;
      END IF;

    ELSE
      v_matched_easygo_ids := v_matched_easygo_ids || v_candidate_ids;
      INSERT INTO public.voucher_reconciliation_results
        (reconciliation_run_id, provider_report_id, easygo_record_id, provider_id, match_status, match_basis, discrepancy_note)
      VALUES
        (v_run_id, v_provider_row.id, NULL, v_provider_row.provider_id, 'duplicate_match', v_provider.match_mode,
         'נמצאו ' || v_candidate_count || ' שוברי EasyGo תואמים לאותו שובר ספק — דורש בדיקה ידנית (IDs: ' ||
         array_to_string(v_candidate_ids, ', ') || ')');
      v_duplicate_count := v_duplicate_count + 1;
    END IF;
  END LOOP;

  -- EasyGo rows this run never matched to any provider row = booked with no
  -- provider-side proof of purchase. This is the financially important
  -- direction of the check, not just a leftover.
  FOR v_easygo_row IN
    SELECT * FROM public.voucher_easygo_records
    WHERE import_batch = p_easygo_batch
      AND NOT (id = ANY (v_matched_easygo_ids))
  LOOP
    IF v_easygo_row.voucher_number IS NULL OR length(trim(v_easygo_row.voucher_number)) = 0 THEN
      INSERT INTO public.voucher_reconciliation_results
        (reconciliation_run_id, provider_report_id, easygo_record_id, provider_id, match_status, discrepancy_note)
      VALUES
        (v_run_id, NULL, v_easygo_row.id, v_easygo_row.provider_id, 'unparseable',
         'שורת EasyGo ללא מספר שובר לקריאה — לא ניתן להשוות');
      v_unparseable_count := v_unparseable_count + 1;
    ELSE
      INSERT INTO public.voucher_reconciliation_results
        (reconciliation_run_id, provider_report_id, easygo_record_id, provider_id, match_status, discrepancy_note)
      VALUES
        (v_run_id, NULL, v_easygo_row.id, v_easygo_row.provider_id, 'missing_in_provider',
         'שובר הוזמן ב-EasyGo אך אין לו גיבוי בדוח הספק');
      v_missing_provider_count := v_missing_provider_count + 1;
    END IF;
  END LOOP;

  RAISE NOTICE '[run_voucher_reconciliation] -- COMPLETE run=% matched=% package_mismatch=% duplicate=% missing_in_easygo=% missing_in_provider=% unparseable=% --',
    v_run_id, v_matched_count, v_mismatch_count, v_duplicate_count, v_missing_easygo_count, v_missing_provider_count, v_unparseable_count;

  RETURN jsonb_build_object(
    'ok', TRUE,
    'reconciliation_run_id', v_run_id,
    'matched', v_matched_count,
    'package_mismatch', v_mismatch_count,
    'duplicate_match', v_duplicate_count,
    'missing_in_easygo', v_missing_easygo_count,
    'missing_in_provider', v_missing_provider_count,
    'unparseable', v_unparseable_count
  );

EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE '[run_voucher_reconciliation] -- ROLLBACK -- % --', SQLERRM;
  RAISE;
END;
$$;

GRANT EXECUTE ON FUNCTION public.run_voucher_reconciliation(UUID, UUID) TO authenticated;
