-- 114_reception_matrix_and_checklist.sql
-- Session 78 — Reception Matrix + Daily Checklist persistence
-- (1) guests.status + 'checked_out' for post-stay archive
-- (2) reception_checklist_entries — per-day audit log with operator attribution

ALTER TABLE public.guests
  DROP CONSTRAINT IF EXISTS guests_status_check;

ALTER TABLE public.guests
  ADD CONSTRAINT guests_status_check
    CHECK (status IN (
      'pending', 'expected', 'room_ready', 'checked_in', 'cancelled', 'checked_out'
    ));

COMMENT ON COLUMN public.guests.status IS
  'pending=imported, expected=arriving, room_ready=room set, checked_in=in-house, checked_out=departed, cancelled=no-show/refund';

CREATE TABLE IF NOT EXISTS public.reception_checklist_entries (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checklist_date      DATE        NOT NULL,
  section_key         TEXT        NOT NULL CHECK (section_key IN ('opening', 'ongoing', 'evening')),
  task_key            TEXT        NOT NULL,
  task_label          TEXT        NOT NULL,
  sort_order          INT         NOT NULL DEFAULT 0,
  is_done             BOOLEAN     NOT NULL DEFAULT false,
  completed_at        TIMESTAMPTZ,
  completed_by        UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  completed_by_name   TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (checklist_date, section_key, task_key)
);

CREATE INDEX IF NOT EXISTS idx_reception_checklist_date
  ON public.reception_checklist_entries (checklist_date DESC);

ALTER TABLE public.reception_checklist_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY reception_checklist_read ON public.reception_checklist_entries
  FOR SELECT TO authenticated USING (true);

CREATE POLICY reception_checklist_write ON public.reception_checklist_entries
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
