-- 176_spa_board_schema.sql
-- WS-A Smart Spa Board — Phase 0: schema + real seed for spa_rooms,
-- spa_therapists, spa_appointments. Built now so Phase 4 (WS-B ops unify,
-- shipped first) has somewhere to point later; board UI itself is Phase 1-3.
--
-- Conflict detection: a room can't hold two overlapping non-cancelled
-- appointments, AND a therapist can't be double-booked across rooms either.
-- Both enforced at the DB layer via partial GiST exclusion constraints (not
-- app-level checks) so a race between two staff members assigning at the
-- same time still can't create a double-booking — FAIL VISIBLE means the
-- conflicting INSERT/UPDATE errors instead of silently overwriting.
--
-- appointment_date + start_time/end_time (not TIMESTAMPTZ) deliberately
-- matches the existing spa_date/spa_time convention already used by
-- guests.spa_date/spa_time and _shared/spaSchedule.ts — naive local time,
-- no timezone math, and the Phase 1-2 write-through to the Golden Profile
-- needs no conversion.

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ─────────────────────────────────────────────────────────────────────────
-- spa_rooms — 20 real rooms (7 couple + 13 single), display_order scoped
-- per room_type to match the seed list order exactly.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.spa_rooms (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT        NOT NULL UNIQUE,
  room_type      TEXT        NOT NULL CHECK (room_type IN ('couple', 'single')),
  display_order  INT         NOT NULL,
  active         BOOLEAN     NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (room_type, display_order)
);

CREATE INDEX IF NOT EXISTS idx_spa_rooms_type_order ON public.spa_rooms (room_type, display_order);

-- ─────────────────────────────────────────────────────────────────────────
-- spa_therapists — 70 placeholder-named slots (real names not yet supplied).
-- linked_profile_id is intentionally unused this cycle — reserved for future
-- therapist-login linkage.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.spa_therapists (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name               TEXT        NOT NULL UNIQUE,
  active             BOOLEAN     NOT NULL DEFAULT true,
  linked_profile_id  UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_spa_therapists_active ON public.spa_therapists (active);

-- ─────────────────────────────────────────────────────────────────────────
-- spa_appointments
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.spa_appointments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guest_id           BIGINT      NOT NULL REFERENCES public.guests(id) ON DELETE CASCADE,
  room_id            BIGINT      NOT NULL REFERENCES public.spa_rooms(id),
  therapist_id       BIGINT      REFERENCES public.spa_therapists(id) ON DELETE SET NULL,
  guest_alert_id     BIGINT      REFERENCES public.guest_alerts(id) ON DELETE SET NULL,

  appointment_date   DATE        NOT NULL,
  start_time         TIME        NOT NULL,
  end_time           TIME        NOT NULL,
  status             TEXT        NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  notes              TEXT,

  created_by         UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (end_time > start_time),

  -- Generated range backing both exclusion constraints below.
  appointment_range  tsrange GENERATED ALWAYS AS (
    tsrange((appointment_date + start_time)::timestamp, (appointment_date + end_time)::timestamp, '[)')
  ) STORED
);

-- Same room, overlapping time, both non-cancelled → reject.
ALTER TABLE public.spa_appointments
  ADD CONSTRAINT spa_appointments_room_no_overlap
  EXCLUDE USING gist (room_id WITH =, appointment_range WITH &&)
  WHERE (status <> 'cancelled');

-- Same therapist, overlapping time, across any room → reject (only once assigned).
ALTER TABLE public.spa_appointments
  ADD CONSTRAINT spa_appointments_therapist_no_overlap
  EXCLUDE USING gist (therapist_id WITH =, appointment_range WITH &&)
  WHERE (status <> 'cancelled' AND therapist_id IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_spa_appointments_date     ON public.spa_appointments (appointment_date);
CREATE INDEX IF NOT EXISTS idx_spa_appointments_guest     ON public.spa_appointments (guest_id);
CREATE INDEX IF NOT EXISTS idx_spa_appointments_room       ON public.spa_appointments (room_id);
CREATE INDEX IF NOT EXISTS idx_spa_appointments_therapist  ON public.spa_appointments (therapist_id);
CREATE INDEX IF NOT EXISTS idx_spa_appointments_alert      ON public.spa_appointments (guest_alert_id);

DROP TRIGGER IF EXISTS trg_spa_appointments_updated_at ON public.spa_appointments;
CREATE TRIGGER trg_spa_appointments_updated_at
  BEFORE UPDATE ON public.spa_appointments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────
-- RLS — same posture as spa_staging (migration 035): any authenticated
-- staff member can read/write, cleaner role is locked out below (matching
-- migration 087's per-table restrictive-policy pattern).
-- ─────────────────────────────────────────────────────────────────────────
ALTER TABLE public.spa_rooms        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spa_therapists   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spa_appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth users can access spa_rooms" ON public.spa_rooms;
CREATE POLICY "auth users can access spa_rooms"
  ON public.spa_rooms FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth users can access spa_therapists" ON public.spa_therapists;
CREATE POLICY "auth users can access spa_therapists"
  ON public.spa_therapists FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth users can access spa_appointments" ON public.spa_appointments;
CREATE POLICY "auth users can access spa_appointments"
  ON public.spa_appointments FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "cleaner_lockdown_spa_rooms" ON public.spa_rooms;
CREATE POLICY "cleaner_lockdown_spa_rooms" ON public.spa_rooms
  AS RESTRICTIVE FOR ALL
  USING      (COALESCE(public.get_true_role(), '') <> 'cleaner')
  WITH CHECK (COALESCE(public.get_true_role(), '') <> 'cleaner');

DROP POLICY IF EXISTS "cleaner_lockdown_spa_therapists" ON public.spa_therapists;
CREATE POLICY "cleaner_lockdown_spa_therapists" ON public.spa_therapists
  AS RESTRICTIVE FOR ALL
  USING      (COALESCE(public.get_true_role(), '') <> 'cleaner')
  WITH CHECK (COALESCE(public.get_true_role(), '') <> 'cleaner');

DROP POLICY IF EXISTS "cleaner_lockdown_spa_appointments" ON public.spa_appointments;
CREATE POLICY "cleaner_lockdown_spa_appointments" ON public.spa_appointments
  AS RESTRICTIVE FOR ALL
  USING      (COALESCE(public.get_true_role(), '') <> 'cleaner')
  WITH CHECK (COALESCE(public.get_true_role(), '') <> 'cleaner');

-- ─────────────────────────────────────────────────────────────────────────
-- Seed: spa_rooms — REAL names supplied by Mike. Re-runnable via ON CONFLICT.
-- Single-room names are TEMPORARY placeholders (Mike has not named them yet)
-- — TODO: rename ספא יחיד 1..13 once Mike supplies the real single-room names.
-- ─────────────────────────────────────────────────────────────────────────
INSERT INTO public.spa_rooms (name, room_type, display_order) VALUES
  ('אבניו 1', 'couple', 1),
  ('חדר 9',   'couple', 2),
  ('חדר 10',  'couple', 3),
  ('אבניו 2', 'couple', 4),
  ('אבניו 3', 'couple', 5),
  ('אבניו 4', 'couple', 6),
  ('טרקלין',  'couple', 7)
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.spa_rooms (name, room_type, display_order)
SELECT 'ספא יחיד ' || n, 'single', n
FROM generate_series(1, 13) AS n
ON CONFLICT (name) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- Seed: spa_therapists — 70 zero-padded placeholder slots (real names not
-- yet supplied). TODO: rename מטפל/ת 01..70 once Mike supplies real names.
-- ─────────────────────────────────────────────────────────────────────────
INSERT INTO public.spa_therapists (name)
SELECT 'מטפל/ת ' || LPAD(n::TEXT, 2, '0')
FROM generate_series(1, 70) AS n
ON CONFLICT (name) DO NOTHING;

COMMENT ON TABLE  public.spa_rooms                      IS 'Smart Spa Board — 20 physical treatment rooms (7 couple + 13 single). Single-room names are placeholders pending Mike.';
COMMENT ON TABLE  public.spa_therapists                 IS 'Smart Spa Board — 70 therapist slots, placeholder names pending Mike; linked_profile_id reserved for future login linkage.';
COMMENT ON TABLE  public.spa_appointments                IS 'Smart Spa Board — confirmed room+therapist assignments; write-through source for guests.spa_date/spa_time.';
COMMENT ON COLUMN public.spa_appointments.therapist_id   IS 'Nullable — board shows a visible ⚠ missing-therapist state until assigned, per FAIL VISIBLE / Disable-Dont-Hide DNA.';
COMMENT ON COLUMN public.spa_appointments.guest_alert_id IS 'Links back to the guest_alerts (alert_type=spa_request) row this appointment was created from, if any.';
