-- 178_spa_activities_sync_schema.sql
-- Smart Spa Board — Phase 0: schema for full Ezgo "פעילויות" (Activities)
-- daily sync. Adds idempotency + provenance columns to spa_appointments,
-- a room-name alias table (editable via UI later, not a hardcoded JS map —
-- Mike needs to fix unmapped rooms without a redeploy), and an unmatched
-- staging table so rows with no guest/room match are never silently
-- dropped (ZERO DATA LOSS, CLAUDE.md §0.1).

-- ─────────────────────────────────────────────────────────────────────────
-- spa_appointments — idempotency + provenance for the new Excel/HTML sync
-- path (Phase 1-4). ezgo_line_id is nullable — not every source format has
-- a stable per-row id (מזהה). Partial unique index (not a plain UNIQUE
-- constraint) so multiple NULLs coexist for rows without one; only rows
-- that DO carry a line id are protected against duplicate re-import.
-- ─────────────────────────────────────────────────────────────────────────
ALTER TABLE public.spa_appointments
  ADD COLUMN IF NOT EXISTS ezgo_line_id   TEXT,
  ADD COLUMN IF NOT EXISTS phone_snapshot TEXT,
  ADD COLUMN IF NOT EXISTS treatment_type TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_spa_appointments_ezgo_line_id
  ON public.spa_appointments (appointment_date, ezgo_line_id)
  WHERE ezgo_line_id IS NOT NULL;

COMMENT ON COLUMN public.spa_appointments.ezgo_line_id   IS 'Ezgo per-row line id (מזהה), when the source report includes one — preferred idempotency key for re-import.';
COMMENT ON COLUMN public.spa_appointments.phone_snapshot IS 'Raw phone as it appeared on the imported row, kept even when guest_id could not be resolved to a Golden Profile.';
COMMENT ON COLUMN public.spa_appointments.treatment_type IS 'Ezgo סוגי טיפולים / תוספות category text (e.g. שוודי) — separate from notes so the board can show it as its own field.';

-- ─────────────────────────────────────────────────────────────────────────
-- spa_room_aliases — Ezgo room-name string → spa_rooms.id. A table (not a
-- hardcoded JS/TS map) so Mike can fix an unmapped room from the SpaBoard
-- unmatched panel without a code deploy.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.spa_room_aliases (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ezgo_name  TEXT        NOT NULL UNIQUE,
  room_id    BIGINT      NOT NULL REFERENCES public.spa_rooms(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_spa_room_aliases_room ON public.spa_room_aliases (room_id);

-- ─────────────────────────────────────────────────────────────────────────
-- spa_import_unmatched — FAIL VISIBLE staging for rows the sync engine
-- could not fully resolve (no guest match and/or no room match). raw_row
-- keeps the entire parsed row so nothing is lost even if resolution logic
-- has a bug — staff can always see exactly what Ezgo sent.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.spa_import_unmatched (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch     UUID        NOT NULL,
  appointment_date DATE        NOT NULL,
  raw_row          JSONB       NOT NULL,
  reason           TEXT        NOT NULL
    CHECK (reason IN ('no_guest_match', 'room_unmapped', 'conflict_23P01', 'suspicious_shared_phone')),
  phone            TEXT,
  guest_name       TEXT,
  room_raw         TEXT,
  start_time       TEXT,
  resolved         BOOLEAN     NOT NULL DEFAULT false,
  resolved_by      UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  resolved_at      TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_spa_import_unmatched_batch    ON public.spa_import_unmatched (import_batch);
CREATE INDEX IF NOT EXISTS idx_spa_import_unmatched_resolved ON public.spa_import_unmatched (resolved);
CREATE INDEX IF NOT EXISTS idx_spa_import_unmatched_date     ON public.spa_import_unmatched (appointment_date);

DROP TRIGGER IF EXISTS trg_spa_import_unmatched_updated_at ON public.spa_import_unmatched;
CREATE TRIGGER trg_spa_import_unmatched_updated_at
  BEFORE UPDATE ON public.spa_import_unmatched
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────
-- RLS — same posture as migration 176 (spa_rooms/spa_therapists/spa_appointments):
-- any authenticated staff member can read/write, cleaner role locked out.
-- ─────────────────────────────────────────────────────────────────────────
ALTER TABLE public.spa_room_aliases    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spa_import_unmatched ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth users can access spa_room_aliases" ON public.spa_room_aliases;
CREATE POLICY "auth users can access spa_room_aliases"
  ON public.spa_room_aliases FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth users can access spa_import_unmatched" ON public.spa_import_unmatched;
CREATE POLICY "auth users can access spa_import_unmatched"
  ON public.spa_import_unmatched FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "cleaner_lockdown_spa_room_aliases" ON public.spa_room_aliases;
CREATE POLICY "cleaner_lockdown_spa_room_aliases" ON public.spa_room_aliases
  AS RESTRICTIVE FOR ALL
  USING      (COALESCE(public.get_true_role(), '') <> 'cleaner')
  WITH CHECK (COALESCE(public.get_true_role(), '') <> 'cleaner');

DROP POLICY IF EXISTS "cleaner_lockdown_spa_import_unmatched" ON public.spa_import_unmatched;
CREATE POLICY "cleaner_lockdown_spa_import_unmatched" ON public.spa_import_unmatched
  AS RESTRICTIVE FOR ALL
  USING      (COALESCE(public.get_true_role(), '') <> 'cleaner')
  WITH CHECK (COALESCE(public.get_true_role(), '') <> 'cleaner');

-- ─────────────────────────────────────────────────────────────────────────
-- Seed: spa_room_aliases — high-confidence mappings only, confirmed with
-- Mike. Couple rooms match Ezgo's own naming directly (seeded 1:1 anyway
-- for a single uniform lookup path in the Phase 2 resolver — no special-
-- casing "exact match vs alias table"). Single rooms: Mike confirmed Ezgo's
-- חדר 1..15 (excluding 9/10, which are couples) map in the SAME sequential
-- order to our ספא יחיד 1..13 placeholders.
--
-- NOT seeded — deliberately left unmapped per Mike's explicit "don't guess"
-- (session note): "ג'קוזי 1". First real import will surface it in
-- spa_import_unmatched (reason='room_unmapped') for Mike to assign via the
-- SpaBoard unmatched panel once he confirms which physical room it is.
-- ─────────────────────────────────────────────────────────────────────────
INSERT INTO public.spa_room_aliases (ezgo_name, room_id)
SELECT alias, r.id
FROM (VALUES
  ('אבניו 1',        'אבניו 1'),
  ('אבניו 2',        'אבניו 2'),
  ('אבניו 3',        'אבניו 3'),
  ('אבניו 4',        'אבניו 4'),
  ('חדר 9',          'חדר 9'),
  ('חדר 10',         'חדר 10'),
  ('סוויטת אבניו 1', 'אבניו 1'),
  ('טרקלין',         'טרקלין'),
  ('חדר 1',          'ספא יחיד 1'),
  ('חדר 2',          'ספא יחיד 2'),
  ('חדר 3',          'ספא יחיד 3'),
  ('חדר 4',          'ספא יחיד 4'),
  ('חדר 5',          'ספא יחיד 5'),
  ('חדר 6',          'ספא יחיד 6'),
  ('חדר 7',          'ספא יחיד 7'),
  ('חדר 8',          'ספא יחיד 8'),
  ('חדר 11',         'ספא יחיד 9'),
  ('חדר 12',         'ספא יחיד 10'),
  ('חדר 13',         'ספא יחיד 11'),
  ('חדר 14',         'ספא יחיד 12'),
  ('חדר 15',         'ספא יחיד 13')
) AS seed(alias, room_name)
JOIN public.spa_rooms r ON r.name = seed.room_name
ON CONFLICT (ezgo_name) DO NOTHING;

COMMENT ON TABLE public.spa_room_aliases     IS 'Ezgo raw room-name string → spa_rooms.id. Editable from the SpaBoard unmatched panel — not a hardcoded map, so Mike can fix a mapping without a deploy.';
COMMENT ON TABLE public.spa_import_unmatched IS 'FAIL VISIBLE staging for Ezgo activities-import rows that could not be fully resolved (guest and/or room). raw_row preserves the entire parsed row — ZERO DATA LOSS.';
