-- 193_spa_therapist_gender_shift_roster.sql
-- Smart Spa Board — Therapist sticky-room + female preference (Architecture A+B, Mike 2026-07-13).
--
-- A) spa_therapists.gender — staff-set, used to warn (not block) when a guest's
--    female_only preference is assigned a non-female therapist.
-- B) spa_shift_roster — advisory "home room for the shift" per therapist/day. Used
--    only to sort the AssignModal therapist picker to the top when it matches the
--    selected room. This is a UI hint, NOT an appointment-blocking exclusion —
--    EZGO import remains the single source of truth for actual appointment
--    room/therapist and is never fought or auto-rewritten by this table.
--    Couple room = two roster rows (same room_id, two different therapists).

ALTER TABLE public.spa_therapists
  ADD COLUMN IF NOT EXISTS gender TEXT NOT NULL DEFAULT 'unknown'
    CHECK (gender IN ('female', 'male', 'unknown'));

COMMENT ON COLUMN public.spa_therapists.gender IS
  'Staff-set; used for female_only guest preference filtering/warnings (soft warning only — never blocks save).';

CREATE TABLE IF NOT EXISTS public.spa_shift_roster (
  id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_date  DATE        NOT NULL,
  room_id           BIGINT      NOT NULL REFERENCES public.spa_rooms(id),
  therapist_id      BIGINT      NOT NULL REFERENCES public.spa_therapists(id) ON DELETE CASCADE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (appointment_date, therapist_id),
  UNIQUE (appointment_date, room_id, therapist_id)
);

CREATE INDEX IF NOT EXISTS idx_spa_shift_roster_date      ON public.spa_shift_roster (appointment_date);
CREATE INDEX IF NOT EXISTS idx_spa_shift_roster_date_room ON public.spa_shift_roster (appointment_date, room_id);

-- RLS — same posture as spa_rooms/spa_therapists/spa_appointments (migration 176).
ALTER TABLE public.spa_shift_roster ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth users can access spa_shift_roster" ON public.spa_shift_roster;
CREATE POLICY "auth users can access spa_shift_roster"
  ON public.spa_shift_roster FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "cleaner_lockdown_spa_shift_roster" ON public.spa_shift_roster;
CREATE POLICY "cleaner_lockdown_spa_shift_roster" ON public.spa_shift_roster
  AS RESTRICTIVE FOR ALL
  USING      (COALESCE(public.get_true_role(), '') <> 'cleaner')
  WITH CHECK (COALESCE(public.get_true_role(), '') <> 'cleaner');

COMMENT ON TABLE public.spa_shift_roster IS
  'Advisory sticky "home room for the shift" per therapist/day — sorts the AssignModal therapist picker to the top when it matches the selected room. UI hint only; never an appointment-blocking exclusion. Couple room = two roster rows (same room_id, two therapists).';
