-- ================================================================
-- Migration 274: Whapi anti-ban velocity guard
--
-- Server-enforced protection for the Suites device (Whapi 1:1 DM outbound)
-- after a real ~24h device restriction on 2026-07-23 caused by a cold bulk
-- send to ~40 waiters (WaiterPulseDispatchPanel, ~2.5s client-side gap —
-- not sufficient on its own; see docs/xos_agent_playbook.md §10). This adds:
--   1. whapi_send_ledger  — per-send audit row, used to compute recency/
--      frequency for the velocity guard (_shared/whapiVelocityGuard.ts).
--   2. whapi_outbound_jobs — durable queue for multi-recipient sends so a
--      browser tab closing mid-blast can't leave the guard's jitter/pacing
--      half-applied (_shared/whapiOutboundQueue.ts + whapi-queue-drain).
--   3. bot_config seeds for the tunable limits + post-ban cooldown state.
--   4. pg_cron schedule draining the queue every 1 minute — independent of
--      the existing 15-minute whatsapp-cron guest-automation cadence, since
--      a UI-triggered "send to 40 waiters" action needs faster draining than
--      that schedule allows.
--   5. Widens notification_log's status CHECK to accept 'rate_limited' —
--      without this, _shared/automationClaim.ts's finalizeDispatchAttempt()
--      would fail its UPDATE on a guard-blocked send, leaving the row stuck
--      at 'processing' (in_flight) instead of a clean, non-retry-gate-
--      counted rate_limited outcome. See _shared/automationRetryGate.ts —
--      buildRetryStateMap only tracks timeout/failed/blocked_by_meta/
--      processing, so rate_limited correctly falls outside cooldown/
--      exhaustion accounting once it's a legal status value.
-- Safe to re-run (idempotent).
-- ================================================================

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── 1. whapi_send_ledger ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.whapi_send_ledger (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone      TEXT   NOT NULL,                 -- recipient phone (bare digits) or group chat_id (…@g.us)
  risk_tier  TEXT   NOT NULL                  -- classification at send time, drives which cap applied
               CHECK (risk_tier IN ('hot', 'warm', 'cold', 'staff', 'group')),
  trigger    TEXT,
  source     TEXT,                            -- calling function, e.g. 'whatsapp-send', 'guest-club-broadcast'
  body_hash  TEXT,                             -- sha256(body) — detects identical-body blasts
  sent_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_whapi_ledger_sent_at   ON public.whapi_send_ledger (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_whapi_ledger_phone     ON public.whapi_send_ledger (phone, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_whapi_ledger_body_hash ON public.whapi_send_ledger (body_hash, sent_at DESC) WHERE body_hash IS NOT NULL;

ALTER TABLE public.whapi_send_ledger ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS whapi_send_ledger_service_only ON public.whapi_send_ledger;
CREATE POLICY whapi_send_ledger_service_only ON public.whapi_send_ledger
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── 2. whapi_outbound_jobs ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.whapi_outbound_jobs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id          UUID NOT NULL,             -- groups every row from one enqueue call for UI progress polling
  status            TEXT NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'sending', 'sent', 'failed', 'cancelled')),
  phone             TEXT NOT NULL,
  name              TEXT,                      -- recipient display name — {{שם}} substitution
  message_template  TEXT NOT NULL,             -- raw template, personalized at send time (not enqueue time)
  risk_tier         TEXT,
  trigger           TEXT,
  source            TEXT,
  scheduled_after   TIMESTAMPTZ NOT NULL DEFAULT NOW(),  -- jitter stagger applied at enqueue time
  attempts          INT NOT NULL DEFAULT 0,
  last_error        TEXT,
  wamid             TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_whapi_jobs_pending
  ON public.whapi_outbound_jobs (scheduled_after)
  WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_whapi_jobs_batch ON public.whapi_outbound_jobs (batch_id);

ALTER TABLE public.whapi_outbound_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS whapi_jobs_read    ON public.whapi_outbound_jobs;
DROP POLICY IF EXISTS whapi_jobs_service ON public.whapi_outbound_jobs;
-- Staff UI (WaiterPulseDispatchPanel) polls batch progress directly.
CREATE POLICY whapi_jobs_read ON public.whapi_outbound_jobs
  FOR SELECT USING (auth.role() = 'authenticated');
-- Only Edge Functions (service role) enqueue/claim/finalize rows.
CREATE POLICY whapi_jobs_service ON public.whapi_outbound_jobs
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- ── 3. bot_config seeds ──────────────────────────────────────────────────
-- Quotas as confirmed 2026-07-23. bulk_max_recipients_per_job is set to 60
-- (not the originally-sketched 5) — the WaiterPulse roster alone runs ~40
-- people and a 5-recipient cap would break that legitimate use outright;
-- the real anti-abuse control for a same-body blast is the mandatory queue
-- (bulk_requires_queue) + jitter stagger + per-recipient body_hash
-- diversification, not a low headcount ceiling. 60 mirrors the existing
-- guest-club-broadcast DEFAULT_LIMIT.
INSERT INTO public.bot_config (config_key, config_value, category, label)
VALUES (
  'whapi_velocity_limits',
  '{
    "global_min_gap_sec": 10,
    "jitter_min_sec": 8,
    "jitter_max_sec": 15,
    "hot":  { "gap_sec": 5,  "per_hour": 40, "per_day": 400 },
    "warm": { "gap_sec": 10, "per_hour": 25, "per_day": 120 },
    "cold": { "gap_sec": 45, "per_hour": 5,  "per_day": 10 },
    "bulk_max_recipients_per_job": 60,
    "bulk_requires_queue": true,
    "post_ban_cooldown_hours": 48,
    "cold_blocked_during_cooldown": true
  }',
  'automation',
  'Whapi anti-ban velocity guard — מכסות ומרווחים'
)
ON CONFLICT (config_key) DO NOTHING;

-- Seeded ACTIVE — a real ban happened today (2026-07-23) from WaiterPulseDispatchPanel's
-- cold bulk to ~40 waiters. cooldown_until = seed time + post_ban_cooldown_hours (48h).
-- Adjust manually (BotConfigPanel or SQL) if the actual ban start time is known to be
-- earlier than this migration's deploy time.
INSERT INTO public.bot_config (config_key, config_value, category, label)
VALUES (
  'whapi_velocity_state',
  jsonb_build_object(
    'last_ban_at', to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'cooldown_until', to_char((NOW() + INTERVAL '48 hours') AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'note', 'Seeded 2026-07-23 — WaiterPulseDispatchPanel cold bulk to ~40 waiters triggered a device restriction. Clear cooldown_until once the device is confirmed healthy again.'
  )::text,
  'automation',
  'Whapi velocity guard — מצב Cooldown אחרי באן'
)
ON CONFLICT (config_key) DO NOTHING;

-- ── 4. notification_log: allow 'rate_limited' as a legal status ─────────
ALTER TABLE public.notification_log DROP CONSTRAINT IF EXISTS notification_log_status_check;
ALTER TABLE public.notification_log
  ADD CONSTRAINT notification_log_status_check
  CHECK (status IN (
    'sent', 'simulated', 'failed', 'timeout', 'blocked_by_meta',
    'processing', 'failed_missing_link', 'duplicate_blocked', 'rate_limited'
  ));

-- ── 5. pg_cron: drain whapi_outbound_jobs every 1 minute ────────────────
-- Deliberately NOT folded into whatsapp-cron's 15-min guest-automation tick —
-- a UI-triggered bulk send needs to finish in minutes, not hours, and this
-- keeps the change isolated from the existing guest pipeline's cadence/logic.
DO $$
BEGIN
  PERFORM cron.unschedule('whapi-queue-drain');
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

SELECT cron.schedule(
  'whapi-queue-drain',
  '* * * * *',
  $$
    SELECT net.http_post(
      url     := 'https://bunohsdggxyyzruubvcd.supabase.co/functions/v1/whapi-queue-drain',
      headers := '{"Content-Type":"application/json"}'::jsonb,
      body    := '{}'::jsonb
    );
  $$
);

-- ================================================================
-- END OF MIGRATION 274
-- ================================================================
